### ISSUE TITLE
Dependency common tables for Create Employee

### ISSUE THREAD

**Issue by mayurisamanta** [mayurisamanta/StaffInsight-Employee-Management-System#17]
**Describe the feature**
Dependency tables for Create Employee 
We will need to have some data for dependency of User entity 

**Scenarios with expected behavior**
# Commons Tables :- 
    - UserType
    - MaritalStatus
    - NamePrefix
    - Gender
    - EmploymentType

1. Create common package
2. Create service, entity, repository and controller package inside common package
3. Move this five entity to common.entity and also respective repo in common.repo
4. Create method (accepts list<entity> and return list<entity>) - for our backend use (Create postman collection and add in resources)
5. viewall (isActive = true should be consider) (use jpa) (to show in frontend)

**Comment by dipeshsingh253** [comment]
Hello @mayurisamanta , I have created the required common entities with required apis. I am closing this issue.
Thanks for your assistance.
