### ISSUE TITLE
Test cases for all the common methods

### ISSUE THREAD

**Issue by mayurisamanta** [mayurisamanta/StaffInsight-Employee-Management-System#21]
**Describe the feature**
Testcases should be there in a common package 
- Controller test
- Service test
- Repo test

**Comment by dipeshsingh253** [comment]
Hello @mayurisamanta , Can you please look at these changes and give me your thoughts on this. 
Also let me know if there are any modifications needed. 

https://github.com/dipeshsingh253/StaffInsight-Employee-Management-System/tree/SI-feature/development_Dipesh
