### ISSUE TITLE
Feature - decide on table structure

### ISSUE THREAD

**Issue by mayurisamanta** [mayurisamanta/StaffInsight-Employee-Management-System#9]
**Describe the feature**
- Decide on Entities required for the application
- Decide which fields to add to Entities

**Additional context**
- It should have fields like isActive to know the status
- It should have fields like CreatedBy, CreatedDate, ModifiedBy, ModifiedDate
- It should have a table for SMS and email template

**Comment by mayurisamanta** [comment]
- Use **SI-feature/development_Mayuri** or **SI-feature/development_Dipesh**  branch for this

**Comment by dipeshsingh253** [comment]
Hello @mayurisamanta , please look at this and let me know for further modifications.

### Entities :

User Entity: Employee Information
	This entity represents the basic information of an employee, such as their first name, last name, date of birth, contact details, and login credentials, address and social account.
- 	id
- 	firstname
- 	lastname
- 	EmployementDetails
- 	Role
- 	dob
- 	email
- 	contact
- 	username
- 	password
- 	List<Address>
- 	List<SocialAccount>


SocialAccount Entity: Social Media Accounts
	This entity represents the social media accounts associated with an employee, such as LinkedIn, Twitter, or other relevant platforms.
- 	accountType
- 	username
- 	url


Address Entity: Employee Address
	This entity represents the address details of an employee, including the apartment number/name, society name, area, landmark, city, state, and postal code.
- 	apartment no./name
- 	societyName
- 	area
- 	landmark
- 	city
- 	state
- 	postalcode


Employment Details Entity: Employment Information
	This entity represents the employment details of an employee, including their job designation, salary, date of joining, department, and the person who referred them.
- 	designation
- 	salary
- 	joinedDate
- 	department
- 	referredBy
- 	contractType
- 	workType
- 	workLocation


User History Entity: User Modification History
	This entity represents the historical changes made to an employee's information, including the date of modification and the person responsible for the modification.
- 	same as user table
- 	modifiedDate
- 	modifiedBy


Daily Attendance Entity: Attendance Tracking
	This entity represents the daily attendance records of employees, including clock-in and clock-out times, late arrivals, overtime hours, and total work hours.
- 	User
- 	clock in
- 	clock out
- 	late
- 	overtime
- 	total work hrs
